### PR TITLE
Add Sass support

### LINKED ISSUE #67: Autocompletion doesn't work with indented sass
**Describe the bug**
The repo kind-of mentions the support for Sass, though from the looks of it I don't believe it does.
What it appears to support is scss-style syntax, and not sass indent / offside-rule syntax.

**To Reproduce**

1. Add to `tsconfig.json`:
```
"plugins": [
  {
    "name": "typescript-plugin-css-modules",
    "options": {
      "classnameTransform": "camelCase"
    }
  }
]
```
2. Create `example.module.sass`:
```sass
.test
  color: red
```
3. Create `example.tsx`:
```tsx
import React, {FunctionComponent} from 'react';
import style from '../styles/example.module.sass';

export const ExampleComponent: FunctionComponent = ({children}) => (
  <h1>
    {children}
  </h1>
);

```
4. See that autocompletion doesn't work (it does with css and scss though):

image

**Expected behavior**
Autocompletion should work correctly and intellisense should show the `test` class.
Should work like with css and scss:

image

**Workspace:**

- OS: W10
- Package version: 2.1.1
- TS version: 3.7.3

Am I missing something here? Seems like indented sass is a pretty popular choice, I don't know why it shouldn't be supported.

### PR DESCRIPTION
**Pull request by judehunter**
Fixes #67 

Adds support for indented sass syntax.
It's done with an `indentedSyntax` conditional field/option which depends on the file type (`.sass` for indented syntax, `.scss` for the one with braces) when rendering to css with the `sass` module.

I decided to omit some fixtures and such because it wouldn't matter whether the original file imported a `.sass` or `.scss` file.

Working autocompletion with indented sass:

image
image

### CODE REVIEW

**Comment by judehunter** [comment]
For some reason the CI test task fails (on snapshots, it seems), though running `npm test` on my machine with the updated snapshots worked flawlessly. I might have screwed something up. :confused:

**Comment by mrmckeb** [comment]
Hi @judehunter, I think you ran into this issue because you were using `npm`. You may have had a different module resolve somewhere, and that's why your snapshots are different.

I ran locally on a clean checkout of your repo - `yarn && yarn test -u` - and updated snapshots, and then pushed. It is all good now ;)

**Comment by mrmckeb** [comment]
Thanks @judehunter, this is now out in v2.1.2.
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.1.2

**Comment by Pytal** [comment]
Stylus has a similar indented syntax could you add support for .styl files?

**Pull request merged**
