### PR TITLE
Add .env SASS_PATH support

### LINKED ISSUE #49: Does not use SASS_PATH environment variable when resolving imports
**Describe the bug**
I have a sass file containing variable/function/mixin stuff located at `/src/theme/_module-basics.scss`.
In my *.env* file I have
```
SASS_PATH=./src/theme
```
which allows me to import *_module-basics.scss* into any CSS module regardless of its location with just
```scss
@import "module-basics";
```  
  
However, after importing such a CSS module into a tsx file, it is typed only as `{}` in VS Code, and I see this in the TS Server log:
```
Info 56   [10:6:34.575] [typescript-plugin-css-modules] Failed Error: Can't find stylesheet to import.
  ╷
1 │ @import "module-basics";
```
Only if I change the `@import` to use a path relative to the module file, like say...
```scss
@import '../theme/module-basics';
```
...do I get a proper type definition for the CSS module.

**To Reproduce**
1. Add the following file/folder structure to a CRA project configured to use `typescript-plugin-css-modules`:
   ```
   (root)
   ├ .env
   └ /src
     ├ App.tsx
     ├ App.modules.scss
     └ /theme
       └ _module-basics.scss
   ```
1. File contents:
   - *.env*
     ```
     SASS_PATH=./src/theme
     ```
   - *_module-basics.scss*
     ```scss
     $nice-color: #FF0080;
     ```
   - *App.modules.scss*
     ```scss
     @import "module-basics";     
     .nicely-colored {
         color: $nice-color;
     }
     ```
   - *App.tsx*
     ```tsx
     /* React, etc. imports */
     
     import styles from './App.module.scss'; // styles assigned Type of {}
     
     function App(props: {}) {
         return (
             <span className={styles["nicely-colored"]}>This is nice.</span> // angry zigzag under styles["nicely-colored"]
         )
     }
     ```
1. Observe `styles` in *App.tsx* is typed as `{}`, causing an angry zigzag in VS Code under `styles["nicely-colored"]`

**Expected behavior**
This plugin and/or its dependencies are able to use the contents of SASS_PATH to resolve `@import "module-basics"` in *App.module.scss*.
Following which, `styles` in *App.tsx* is provided a Type based on the classes/ids in *App.module.scss*, so there is no angry under `styles["nicely-colored"]`.

**Desktop**
- OS: Windows 10

### PR DESCRIPTION
**Pull request by PsiRadish**
Fixes #49 

Adds support for resolving `@import`s in `*.scss` files using the paths defined in `SASS_PATH` in a `.env` file at the project root.

Works by reading in the `.env` file during initialization and adding its `SASS_PATH` value (after some fix-up to relative paths) to `process.env.SASS_PATH`, where `dart-sass` will find it and use it.

Unfortunately, like #50 the other currently pending pull request on this repo, I too have failing `*.scss` tests with empty received snapshot, even with no modifications from upstream `origin/develop`.  All other tests are passing.

### CODE REVIEW

**Comment by mrmckeb** [comment]
Thanks @PsiRadish, this looks good - I'm just unsure as to if we should be using this - or instead just use the `dotenv` package?

I also think we might want to allow people to pass in a file name as an option. What do you think?

**Comment by mrmckeb** [comment]
@PsiRadish Can we make a change to this PR to try to load that file with `dotenv`?

**Comment by PsiRadish** [comment]
> I also think we might want to allow people to pass in a file name as an option. What do you think?

I said the same in a `MAYBE TODO` in comments, so yeah, sounds good.

> @PsiRadish Can we make a change to this PR to try to load that file with `dotenv`?

That is how I had it work in [my first commit](https://github.com/mrmckeb/typescript-plugin-css-modules/pull/51/commits/24c91c576470acef3aaa015e0de2e724cd5ee4e7).  However, I wasn't _sure_ there weren't other environment variables `typescript-plugin-css-modules` or its dependencies used that one would _not_ want set with values from a "random" React project `.env` file.  If you _are_ sure (or at least surer than I), then yeah, why not?

**Comment by mrmckeb** [comment]
Thanks for this work! I'll make some changes, and then release tomorrow.

**Comment by mrmckeb** [comment]
Hi @PsiRadish, we've just released v2.0.0 which includes this PR and other changes.

Release notes and migration steps can be found here: https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.0.0

Please let me know if you have any other issues or feedback! And thanks for your patience.

**Pull request merged**
