### PR TITLE
Add TypeScript server logs for exceptions

### LINKED ISSUE #36: tsserver logging
**Is your feature request related to a problem? Please describe.**
There is no logging throughout the plugin and errors are just getting swallowed, for example in [cssSnapshots](https://github.com/mrmckeb/typescript-plugin-css-modules/blob/develop/src/helpers/cssSnapshots.ts#L63), the catch block returns `{}`. 

```
    return extractICSS(processedCss.root).icssExports;
  } catch (e) {
    return {};
  }
```

It took a lot of painstaking logging to find out that an exception was being swallowed.

**Describe the solution you'd like**

There is a logger that gets passed into the `create` function as part of the `info` object, e.g.

```javascript
  function create(info) {
      var logger = info.project.projectService.logger;
```

There is a `TSS_LOG` environment variable that when set allows you to log to the console or a file, e.g.

```bash
export TSS_LOG="-level verbose -file /Users/me/.tslog"
```

You can then see the log messages, it took me a long time to find the actual error.

This is not a criticism, thank you for writing this library, I think it most needed.

### PR DESCRIPTION
**Pull request by dagda1**
Resolves #36.

The logger gets passed in with the `info` object in the language service `create` function which is a bit annoying so you need to pass it to any function needing it.

I've wrapped it in a very simple `LanguageServiceLogger`.

I've also maybe controversially changed `cssSnapshots.ts` from functions into a file with the only reason being, that I don't have to pass the `Logger` to any function that requires it. Could change it back.

### CODE REVIEW

**Comment by mrmckeb** [comment]
@dagda1, this is great - thanks. There are a few things I'd change, but I don't have a lot of time and as they're stylistic things, I think it's better to merge this and release, and I can just make the changes at a later date.

I'll get @lianapache to review too, and then we can merge and release.

**Comment by mrmckeb** [comment]
Also, on a side note, it looks like the email address you have configured locally hasn't been added to GitHub.
 
image

**Comment by dagda1** [comment]
@mrmckeb I'm always interested in feedback if you have time, even if it is stylistic.  Thanks for the shout out about the email, I recently deleted an old google account that was in my git.config.

**Comment by dagda1** [comment]
@mrmckeb is the PR good to go?

**Comment by mrmckeb** [comment]
Yes, thanks! I plan to merge and release tomorrow.

**Comment by mrmckeb** [comment]
I know you asked for feedback too - it was stylistic in the sense that we try to keep a functional-approach in this package, but that was all. Thanks for the contribution!

**Comment by mrmckeb** [comment]
You can pull this with the beta tag (`@beta`) or as `1.3.0-beta.0` - this should be released properly in the coming days. Again, apologies, I'm in travel right now and literally published from a train.

**Comment by dagda1** [comment]
@mrmckeb no apologies necessary, thank you for creating this as it is something I have been wanting to do

**Comment by mrmckeb** [comment]
This is now in 1.3.1 (out of beta). Thanks again!

**Pull request merged**
