### PR TITLE
fix sass tilde importer partials support

### PR DESCRIPTION
**Pull request by dennispg**
This change fixes a bug when importing partial sass files from `node_modules` which happen to have their basename exist also in some part of the dirname. 

For example, `@import '~sass-mq/mq';` should resolve to `node_modules/sass-mq/_mq.scss` but instead is looking for `node_modules/sass-_mq/mq.scss`.

### CODE REVIEW

**Review by mrmckeb — COMMENTED** [review]
Thanks for this! Are you able to add a test or two to cover the change here?

**Comment by dennispg** [comment]
So I had taken a look at trying to add a test to cover this, but I didn't see any examples of modules or dependent modules that were already a part of the package.json that I could use. Would it be ok for me to loop in, for example, sass-mq as a devDependency to accomplish this, or is there a better way to mock it maybe?

**Comment by dennispg** [comment]
@mrmckeb I've gone ahead and done a significant refactoring here, and split out the resolve bits into it's own factor so that test can be written against it directly. And I added the relevant tests as well.

**Comment by dennispg** [comment]
Also I removed the part where it was walking the file directory tree.. I don't think that was accomplishing what it was expected to, and was just not necessary.

**Review by mrmckeb — APPROVED** [review]

**Comment by mrmckeb** [comment]
Thanks for this, I'm working through some refactoring today/tomorrow, but will release this over the course of the weekend.

**Pull request merged**
