### PR TITLE
Use let instead of const

### LINKED ISSUE #97: Lots of errors produced in WebStorm IDE with this plugin
**Describe the bug**
When including this plugin in my `tsconfig.json`, the Intellij WebStorm IDE reports hundreds of errors that look like this:
```Error:(54, 33) TS1155: 'const' declarations must be initialized.```
image

When I remove this plugin, these errors go away.

**To Reproduce**
Use WebStorm in a project with this plugin. My `tsconfig` using ts `3.9.5`:
```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "baseUrl": ".",
    "rootDir": ".",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "paths": {
      "~/*": ["src/*"]
    },
    "importsNotUsedAsValues": "preserve",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "isolatedModules": true,
    "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "customMatcher": "\\.css$"
        }
      }
    ]
  },
  "exclude": [
    "./node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "src/setupTests.ts"
  ]
}

```

The TypeScript window in the IDE will call the TS service and find errors for you.

**Expected behavior**
These errors wouldn't show up.

**Screenshots**
see above.

another very simple example:

image
image

**Desktop (please complete the following information):**

- OS: Mac OSX Catalina

**Additional context**
We use CSS modules and some PostCSS features, though these errors seem to pop up in files that don't do anything fancy like PostCSS's nesting, too.

### PR DESCRIPTION
**Pull request by ekilah**
Fixes #97

This avoids errors in the Webstorm IDE's TypeScript console.

### CODE REVIEW

**Comment by ekilah** [comment]
I guess I should clarify, it _seemed_ to resolve things, but maybe the CI failure means that it was just broken in a different way? Unclear. I'll let you tell me, I am just observing symptoms :)

**Comment by RyanChristian4427** [comment]
The tests are only failing because you didn't update the snapshots.

Did you not try to run the tests locally or read the output from the CI?

**Comment by ekilah** [comment]
I did nothing like that no. I don't see any instructions on the repo's markdown files describing how to do what you are implying is necessary. Let me know and I can try those things.

**Comment by RyanChristian4427** [comment]
This is the output from the CI. It's a snapshot test. It's saying it expected `const` but found `let` in it's place. 

```
FAIL src/helpers/__tests__/getDtsSnapshot.test.ts (8.839s)
  ● utils / cssSnapshots › with file 'test.module.css' › createExports › should create an exports file

    expect(received).toMatchSnapshot()

    Snapshot name: `utils / cssSnapshots with file 'test.module.css' createExports should create an exports file 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -1,6 +1,6 @@
    - declare const classes: {
    + declare let classes: {
      'classA': string;
        'ClassB': string;
        'class-c': string;
        'class_d': string;
        'parent': string;


      72 |             options: {},
      73 |           });
    > 74 |           expect(exports).toMatchSnapshot();
         |                           ^
      75 |         });
      76 |       });
      77 |
```

Running tests locally and/or reading CI output is kinda important. 

You'll need to update the snapshots.

**Comment by ekilah** [comment]
So is having clear expectations and instructions on a project that anticipates public input from people unfamiliar with the codebase. Not getting a reply in 3 weeks isn't a good incentive to go diving into the various test suites to fix CI either.

But I'm not here to complain, I'm just trying to report an issue and help solve it. I don't think the subtle condescension about the importance of doing this and that are productive or earned.

If you don't mind posting the set of commands necessary to do what you're asking for, I can do that next time I have some time. You neglected to include instructions.

**Comment by RyanChristian4427** [comment]
Firstly, I'm not connected with this project in any way, shape, or form. Just came across it tonight. 

> Not getting a reply in 3 weeks isn't a good incentive to go diving into the various test suites to fix CI either.

A good incentive is the failing test suite and CI though.

> I don't think the subtle condescension about the importance of doing this and that are productive or earned.

You didn't even try to run the tests locally or even glance at the CI output to see **why** the tests were failing. I'm not exactly sure what you expect?

> If you don't mind posting the set of commands necessary to do what you're asking for

There are no magic commands. Completely resetting the snapshots is almost never recommended (especially not from a PR) as that opens up the possibility for incorrect snapshots. You should fix them by using a search & replace or by hand. It's just swapping out `const` with `let`.

**Comment by ekilah** [comment]
Thanks for your valuable insight.

**Comment by mrmckeb** [comment]
Sorry @ekilah, I've been away and had a few personal things to attend to, and I didn't get back to this as soon as I wanted to.

As @RyanChristian4427 said, the snapshots are currently failing here, which need to be fixed. If you can get those fixed, I can help get this merged and released. As the tests are in Jest, you can simply run the command and pass `-u` to update snapshots, or press `u` if in interactive mode. You can read more about snapshot testing in Jest [here](https://jestjs.io/docs/en/snapshot-testing).

Have you tested these changes? If so, can you please provide a before and after screenshot too? I don't have Webstorm installed (I use VSCode).

**Comment by ekilah** [comment]
Thanks for getting back to me!

I rebased to get the TS 4.0 fix in #101, and updated the snapshots with `yarn jest -u`.

Without my patch:
Screen Shot 2020-09-12 at 11 48 30 AM

With my patch:
Screen Shot 2020-09-12 at 12 08 10 PM

Note that this just prevents the spammy errors in WebStorm; as far as I can tell, this plugin doesn't add any functionality in WebStorm. Without this plugin, WebStorm can already do this:

Screen Shot 2020-09-12 at 12 10 48 PM

That last statement somewhat conflicts with #96 - the OP seems to get some use out of this plugin that I'm not seeing, but at least this PR fixes the errors.

**Comment by mrmckeb** [comment]
Thanks for that - so to clarify, this fix is because the plugin is in your project for those in your team using VSCode, but you don't need it. 

VSCode also has a few extensions that can do this, but obviously each user needs to install and configure those themselves.

**Review by mrmckeb — APPROVED** [review]

**Comment by mrmckeb** [comment]
Hi @ekilah, I've published this as `2.6.0-beta.0`. It's built with TypeScript 4.0, and also contains a minor change to make the classnames readonly (as they should be).

Please let me know if this a) fixes your problem, and b) causes any issues for you or colleagues.

**Comment by ekilah** [comment]
replied over at https://github.com/mrmckeb/typescript-plugin-css-modules/issues/97#issuecomment-692285923

**Pull request merged**
