### PR TITLE
Support a custom TS transformer for final DTS output

### PR DESCRIPTION
**Pull request by joeljeske**
I am a new user of this plugin and I think it is awesome! 

Pardon my assumptions in posting a PR before we've discussed it. I wouldn't be offended if you rejected the idea, however, I think it is a nice feature that has merit and could prevent excess feature requests from this plugin in the future. 

The idea here is to provide a custom transformation function to allow users to transform the generated DTS before it is handed back to TSServer. This allows the dev to add additional info to the generated DTS, or generate a new set altogether. 

This is useful to me as I generate my own set of JS for runtime that does not quite match the standard CSS Module output that is generated from this plugin. 

Please let me know if you think this addition has merit and/or if there are changes you would like. 

Many thanks for an awesome plugin that solves a real pain point!

### CODE REVIEW

**Comment by mrmckeb** [comment]
Hi @joeljeske, thanks for the PR. This is quite interesting - and sorry for the late reply, I was on a business trip.

Basically, this is a post-render hook that allows you to redefine the DTS output. This means that people can add enums, etc.

I'm not opposed to this, although I'd like to think about naming a little more. @lianapache what do you think?

My only concern is that I'm not sure it would have wide usage - but it's also fairly simple, so I don't think supporting it will be a problem.

@joeljeske Do you think it makes more sense to just provide the classnames, rather than the proposed DTS, and let the user completely define the template?

**Comment by joeljeske** [comment]
I think there are a variety of different things people could add, enum is just one of them, and not actually the one I would be using. 

My particular use case is generating real react components from the CSS Module JSON. This would be importing react components into a TSX file and use them directly as opposed to using classes.className. 

Of course, this is very different from the standard css modules transform, but runs into the same sub-standard coding experience that this plugin solves. 


I think that as the CSS in JS landscape is churning right now, that we may continue to see newer solutions arise, and making them Type safe seems like it will always be a challenge. My thought was this would be a non-invasive way to support others crazy ideas without needing to make any big changes. 

What do you think?

**Comment by mrmckeb** [comment]
Sorry @joeljeske, I've just pinged @lianapache again for her opinion.

I agree with you that this could be useful for some people - as we'd basically be allowing them to use their own templates.

**Comment by lianapache** [comment]
@joeljeske  @mrmckeb Sorry for the long response.
I think this feature could be useful 🙂 @mrmckeb  Maybe we could release a beta to try it out?

**Comment by mrmckeb** [comment]
OK, great! I'll look at this today or tomorrow, will make a few changes, and release. Thanks @joeljeske and @lianapache

**Comment by mrmckeb** [comment]
Thanks @joeljeske, this is now released at v2.2.0 - sorry it took a while to turn it around.

**Pull request merged**
