### PR TITLE
fix: update module resolution for non-relative paths

### LINKED ISSUE #227: Autocomplete not working with global path
**Describe the bug**
Next.js often use global path alias `@` for sources (defines in `tsconfig.json` through `"baseUrl": "."` and `"paths": { "@/*": ["./src/*"] }`).  
And in this case autocomplete for CSS-module doesn't work.

**To Reproduce**

1. Go to [sandbox sources](https://codesandbox.io/p/sandbox/silly-cherry-yn2crj?file=%2Fsrc%2Fpages%2Findex.tsx%3A1%2C30)
2. Make sure first line is defined with absolute path: `import styles from "@/styles/home.module.scss";`
3. Over cursor to variable `styles` on line 8.
4. See the variable definition as 

image

**Expected behavior**
Please modify sources: 
1. comment first line with absolute path `import styles from "@/styles/home.module.scss";`
2. uncomment second line with relative path `import styles from "../styles/home.module.scss";`
3. Hover variable `styles` on line 8.

In this case you will see the valid definition with CSS-classes as object keys like:

image

**TypeScript version**: 5.0.4
**Plugin version**: 5.0.1

### PR DESCRIPTION
**Pull request by smoores-dev**
Fixes #227.

This change generalizes "module resolution with failed lookup locations" so that it works for newer implementations of the typescript language server,  which provide such information in the response for `resolveModuleNameLiterals`, rather than implementing a separate `getResolvedModuleWithFailedLookupLocationsFromCache`.

Tested locally in a project using Typescript 5 and path aliases, and imports like:

```ts
import {
  editorContainer,
  tableOfContentsContainer,
} from "@/components/app.module.css"
```

which were failing before this change now successfully show type information and support "Go to Definition", etc.

### CODE REVIEW

**Comment by SMores** [comment]
Hey @mrmckeb! I imagine you've got a ton of other stuff going on, but let me know if you have a chance to take a look at this any time soon! I'd love to get your thoughts. Thanks so much for all of your work on this plugin!

**Comment by LoiLock** [comment]
Any updates?

**Review by mrmckeb — APPROVED** [review]
Thanks @smoores-dev - this looks great to me. Sorry for the very slow turnaround, I try to check in once every 2-3 weeks (unless there's a critical issue) but had a bit more going on recently.

**Comment by mrmckeb** [comment]
Closing and reopening to trigger tests, etc.

**Comment by mrmckeb** [comment]
I plan to get this out in the next day or two - I also need to set up automatic releases for this repo.

**Comment by mrmckeb** [comment]
Sorry this took so long. Released:
https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v5.0.2

**Pull request merged**
